# Generated by Django 3.0.7 on 2020-06-26 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_users',
            name='username',
            field=models.CharField(max_length=35, unique=True),
        ),
    ]
