# Generated by Django 3.0.7 on 2020-06-26 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogPost', '0002_auto_20200626_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_text', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_publish', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogPost.Blog_Users')),
            ],
        ),
    ]
