# Generated by Django 3.0.7 on 2020-06-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPost', '0005_auto_20200626_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='blog_title',
            field=models.CharField(max_length=100),
        ),
    ]
